@startuml
'https://plantuml.com/class-diagram
'定义工厂方法模式'

abstract class Product
class ConcreteProduct

abstract class Creator{
   + {abstract} factoryMethod()
   +  anOperation()
}
class ConcreteCreator{
    +  factoryMethod()
}

Product <|-- ConcreteProduct
Creator <|-- ConcreteCreator
ConcreteCreator -left-> ConcreteProduct

@enduml